src/Entity/Matiere.php
<?php

namespace App\Entity;

use App\Repository\MatiereRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Ressource;



#[ORM\Entity(repositoryClass: MatiereRepository::class)]
class Matiere
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $volume_horaire = null;

    #[ORM\ManyToOne(inversedBy: 'matieres')]
    private ?User $enseignant = null;
    /**
     * @var Collection<int, Ressource>
     */
    #[ORM\ManyToMany(targetEntity: Ressource::class, mappedBy: "matieres")]
    private Collection $ressources;


    /**
     * @var Collection<int, Creneau>
     */
    #[ORM\OneToMany(targetEntity: Creneau::class, mappedBy: 'matiere')]
    private Collection $creneaux;

    public function __construct()
    {
        $this->ressources = new ArrayCollection();
        $this->creneaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getVolumeHoraire(): ?int
    {
        return $this->volume_horaire;
    }

    public function setVolumeHoraire(int $volume_horaire): static
    {
        $this->volume_horaire = $volume_horaire;

        return $this;
    }

    public function getEnseignant(): ?User
    {
        return $this->enseignant;
    }

    public function setEnseignant(?User $enseignant): static
    {
        $this->enseignant = $enseignant;

        return $this;
    }

    /**
     * @return Collection<int, Creneau>
     */
    public function getCreneaus(): Collection
    {
        return $this->creneaux;
    }

    public function addCreneau(Creneau $creneau): static
    {
        if (!$this->creneaux->contains($creneau)) {
            $this->creneaux->add($creneau);
            $creneau->setMatiere($this);
        }

        return $this;
    }

    public function removeCreneau(Creneau $creneau): static
    {
        if ($this->creneaux->removeElement($creneau)) {
            // set the owning side to null (unless already changed)
            if ($creneau->getMatiere() === $this) {
                $creneau->setMatiere(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ressource>
     */
    public function getRessources(): Collection
    {
        return $this->ressources;
    }

    public function addRessource(Ressource $ressource): static
    {
        if (!$this->ressources->contains($ressource)) {
            $this->ressources->add($ressource);
            $ressource->addMatiere($this);
        }

        return $this;
    }

    public function removeRessource(Ressource $ressource): static
    {
        if ($this->ressources->removeElement($ressource)) {
            $ressource->removeMatiere($this);
        }

        return $this;
    }

}

src/Form/MatiereType.php
<?php

namespace App\Form;

use App\Entity\Matiere;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatiereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('volume_horaire')
            ->add('enseignant', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'last_name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Matiere::class,
        ]);
    }
}

src/Controller/MatiereController.php
<?php

namespace App\Controller;

use App\Entity\Matiere;
use App\Form\MatiereType;
use App\Repository\MatiereRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/matiere')]
final class MatiereController extends AbstractController
{
    #[Route(name: 'app_matiere_index', methods: ['GET'])]
    public function index(MatiereRepository $matiereRepository): Response
    {
        return $this->render('matiere/index.html.twig', [
            'matieres' => $matiereRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_matiere_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $matiere = new Matiere();
        $form = $this->createForm(MatiereType::class, $matiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($matiere);
            $entityManager->flush();

            return $this->redirectToRoute('app_matiere_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('matiere/new.html.twig', [
            'matiere' => $matiere,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_matiere_show', methods: ['GET'])]
    public function show(Matiere $matiere): Response
    {
        return $this->render('matiere/show.html.twig', [
            'matiere' => $matiere,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_matiere_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Matiere $matiere, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MatiereType::class, $matiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_matiere_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('matiere/edit.html.twig', [
            'matiere' => $matiere,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_matiere_delete', methods: ['POST'])]
    public function delete(Request $request, Matiere $matiere, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$matiere->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($matiere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_matiere_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/matiere/_delete_form.html.twig
<form method="post" action="{{ path('app_matiere_delete', {'id': matiere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ matiere.id) }}">
    <button class="btn">Delete</button>
</form>

templates/matiere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/matiere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Matiere{% endblock %}

{% block body %}
    <h1>Modifier Matiere</h1>

    {{ include('matiere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_matiere_index') }}">back to list</a>

    {{ include('matiere/_delete_form.html.twig') }}
{% endblock %}

templates/matiere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matiere{% endblock %}

{% block body %}
    <h1>Matiere</h1>

    <table class="table">
        <thead>
            <tr>
                <th>utilisateur ID</th>
                <th>Nom</th>
                <th>Volume_horaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for matiere in matieres %}
            <tr>
                <td>{{ matiere.id }}</td>
                <td>{{ matiere.name }}</td>
                <td>{{ matiere.volumeHoraire }}</td>
                <td>
                    <a href="{{ path('app_matiere_show', {'id': matiere.id})}}" class="btn btn-info">show</a>
                    <a href="{{ path('app_matiere_edit', {'id': matiere.id})}}" class="btn btn-warning">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_matiere_new')}}" class="btn btn-success">Ajouter matiere</a>
{% endblock %}

templates/matiere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Matiere{% endblock %}

{% block body %}
    <h1>Ajouter Matiere</h1>

    {{ include('matiere/_form.html.twig') }}

    <a href="{{ path('app_matiere_index') }}"   class="btn btn-secondary">back to list</a>
{% endblock %}

templates/matiere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matiere{% endblock %}

{% block body %}
    <h1>Matiere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Matiere ID</th>
                <td>{{ matiere.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ matiere.name }}</td>
            </tr>
            <tr>
                <th>Volume_horaire</th>
                <td>{{ matiere.volumeHoraire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_matiere_index') }}">back to list</a>

    <a href="{{ path('app_matiere_edit', {'id': matiere.id}) }}">edit</a>

    {{ include('matiere/_delete_form.html.twig') }}
{% endblock %}