src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $year_level = null;

    /**
     * @var Collection<int, Creneau>
     */
    #[ORM\OneToMany(targetEntity: Creneau::class, mappedBy: 'promotion')]
    private Collection $creneaux;

    public function __construct()
    {
        $this->creneaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getYearLevel(): ?string
    {
        return $this->year_level;
    }

    public function setYearLevel(int $year_level): static
    {
        $this->year_level = $year_level;

        return $this;
    }

    /**
     * @return Collection<int, Creneau>
     */
    public function getCreneaux(): Collection
    {
        return $this->creneaux;
    }

    public function addCreneau(Creneau $creneaux): static
    {
        if (!$this->creneaux->contains($creneaux)) {
            $this->creneaux->add($creneaux);
            $creneaux->setPromotion($this);
        }

        return $this;
    }

    public function removeCreneau(Creneau $creneaux): static
    {
        if ($this->creneaux->removeElement($creneaux)) {
            // set the owning side to null (unless already changed)
            if ($creneaux->getPromotion() === $this) {
                $creneaux->setPromotion(null);
            }
        }

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('year_level')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/promotion')]
final class PromotionController extends AbstractController
{
    #[Route(name: 'app_promotion_index', methods: ['GET'])]
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_promotion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_show', methods: ['GET'])]
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_promotion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_delete', methods: ['POST'])]
    public function delete(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promotion{% endblock %}

{% block body %}
    <h1>Edit Promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_promotion_index') }}">back to list</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion index{% endblock %}

{% block body %}
    <h1>Promotion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Year_level</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.yearLevel }}</td>
                <td>
                    <a href="{{ path('app_promotion_show', {'id': promotion.id}) }}">show</a>
                    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_promotion_new') }}">Create new</a>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <h1>Create new Promotion</h1>

    {{ include('promotion/_form.html.twig') }}

    <a href="{{ path('app_promotion_index') }}">back to list</a>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>Year_level</th>
                <td>{{ promotion.yearLevel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_promotion_index') }}">back to list</a>

    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}