src/Entity/Enseignant.php
<?php

namespace App\Entity;

use App\Repository\EnseignantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnseignantRepository::class)]
class Enseignant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'enseignant', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $utilisateur = null;

    #[ORM\ManyToOne(inversedBy: 'enseignants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeEnseignant $TypeEnseignant = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(User $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getTypeEnseignant(): ?TypeEnseignant
    {
        return $this->TypeEnseignant;
    }

    public function setTypeEnseignant(?TypeEnseignant $TypeEnseignant): static
    {
        $this->TypeEnseignant = $TypeEnseignant;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true,nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    /**
     * @var Collection<int, Matiere>
     */
    #[ORM\OneToMany(targetEntity: Matiere::class, mappedBy: 'enseignant')]
    private Collection $matieres;

    /**
     * @var Collection<int, Ressource>
     */
    #[ORM\OneToMany(targetEntity: Ressource::class, mappedBy: 'referent')]
    private Collection $ressources;

    /**
     * @var Collection<int, Creneau>
     */
    #[ORM\OneToMany(targetEntity: Creneau::class, mappedBy: 'enseignant')]
    private Collection $creneaux;

    #[ORM\OneToOne(mappedBy: 'utilisateur', cascade: ['persist', 'remove'])]
    private ?Enseignant $enseignant = null;




    public function __construct()
    {
        $this->matieres = new ArrayCollection();
        $this->ressources = new ArrayCollection();
        $this->creneaux = new ArrayCollection();
        
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;

        if (in_array('ROLE_PROF_REFERENT', $this->roles)) {
            $roles[] = 'ROLE_PROF_REFERENT';
        }

        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }
    public function getUserIdentifier(): string
    {
        // Retourne une propriété unique identifiant l'utilisateur, par exemple le username ou l'email
        return $this->email; // ou $this->email selon ce que vous utilisez
    }

    public function eraseCredentials():void
    {
        // Si vous stockez des données sensibles temporaires dans l'entité utilisateur, effacez-les ici.
        // $this->plainPassword = null;
    }
    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Matiere>
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matiere $matiere): static
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres->add($matiere);
            $matiere->setEnseignant($this);
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): static
    {
        if ($this->matieres->removeElement($matiere)) {
            // set the owning side to null (unless already changed)
            if ($matiere->getEnseignant() === $this) {
                $matiere->setEnseignant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ressource>
     */
    public function getRessources(): Collection
    {
        return $this->ressources;
    }

    public function addRessource(Ressource $ressource): static
    {
        if (!$this->ressources->contains($ressource)) {
            $this->ressources->add($ressource);
            $ressource->setReferent($this);
        }

        return $this;
    }

    public function removeRessource(Ressource $ressource): static
    {
        if ($this->ressources->removeElement($ressource)) {
            // set the owning side to null (unless already changed)
            if ($ressource->getReferent() === $this) {
                $ressource->setReferent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Creneau>
     */
    public function getCreneaus(): Collection
    {
        return $this->creneaux;
    }

    public function addCreneau(Creneau $creneau): static
    {
        if (!$this->creneaux->contains($creneau)) {
            $this->creneaux->add($creneau);
            $creneau->setEnseignant($this);
        }

        return $this;
    }

    public function removeCreneau(Creneau $creneau): static
    {
        if ($this->creneaux->removeElement($creneau)) {
            // set the owning side to null (unless already changed)
            if ($creneau->getEnseignant() === $this) {
                $creneau->setEnseignant(null);
            }
        }

        return $this;
    }

    public function getEnseignant(): ?Enseignant
    {
        return $this->enseignant;
    }

    public function setEnseignant(Enseignant $enseignant): static
    {
        // set the owning side of the relation if necessary
        if ($enseignant->getUtilisateur() !== $this) {
            $enseignant->setUtilisateur($this);
        }

        $this->enseignant = $enseignant;

        return $this;
    }


}

src/Form/EnseignantType.php
<?php

namespace App\Form;

use App\Entity\Enseignant;
use App\Entity\TypeEnseignant;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Doctrine\ORM\EntityRepository;

class EnseignantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('utilisateur', EntityType::class, [
                'class' => User::class,
                'choice_label' => function (User $user) {
                    return $user->getFirstName() . ' ' . $user->getLastName();
                },
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.last_name', 'ASC');
                },
                'label' => 'Sélectionner un utilisateur'
            ])
            ->add('typeEnseignant', EntityType::class, [
                'class' => TypeEnseignant::class,
                'choice_label' => 'type',
                'label' => 'Type d’enseignant'
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Ajouter l’enseignant'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enseignant::class,
        ]);
    }
}

src/Controller/EnseignantController.php
<?php

namespace App\Controller;

use App\Entity\Enseignant;
use App\Form\EnseignantType;
use App\Repository\EnseignantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/enseignant')]
final class EnseignantController extends AbstractController
{
    #[Route(name: 'app_enseignant_index', methods: ['GET'])]
    public function index(EnseignantRepository $enseignantRepository): Response
    {
        return $this->render('enseignant/index.html.twig', [
            'enseignants' => $enseignantRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_enseignant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $enseignant = new Enseignant();
        $form = $this->createForm(EnseignantType::class, $enseignant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($enseignant);
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enseignant/new.html.twig', [
            'enseignant' => $enseignant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignant_show', methods: ['GET'])]
    public function show(Enseignant $enseignant): Response
    {
        return $this->render('enseignant/show.html.twig', [
            'enseignant' => $enseignant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_enseignant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enseignant $enseignant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EnseignantType::class, $enseignant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enseignant/edit.html.twig', [
            'enseignant' => $enseignant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignant_delete', methods: ['POST'])]
    public function delete(Request $request, Enseignant $enseignant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enseignant->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($enseignant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/enseignant/_delete_form.html.twig
<form method="post" action="{{ path('app_enseignant_delete', {'id': enseignant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enseignant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enseignant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enseignant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enseignant{% endblock %}

{% block body %}
    <h1>Modifier Enseignant</h1>

    {{ include('enseignant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_enseignant_index') }}">Retour</a>

    {{ include('enseignant/_delete_form.html.twig') }}
{% endblock %}

templates/enseignant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Enseignants{% endblock %}

{% block body %}
    <h1>Liste des Enseignants</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for enseignant in enseignants %}
            <tr>
                <td>{{ enseignant.utilisateur.lastName }}</td>
                <td>{{ enseignant.utilisateur.firstName }}</td>
                <td>{{ enseignant.typeEnseignant.type }}</td>
                <td>
                    <a href="{{ path('app_enseignant_show', {'id': enseignant.id}) }}" class="btn btn-info">Voir</a>
                    <a href="{{ path('app_enseignant_edit', {'id': enseignant.id}) }}" class="btn btn-warning">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun enseignant trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_enseignant_new') }}" class="btn btn-success">Créer un nouvel enseignant</a>
{% endblock %}

templates/enseignant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Enseignant{% endblock %}

{% block body %}
{{ form_start(form, {'attr': {'class': 'needs-validation'}}) }}

<div class="mb-3">
    {{ form_label(form.utilisateur, 'Utilisateur', {'label_attr': {'class': 'form-label'}}) }}
    {{ form_widget(form.utilisateur, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="mb-3">
    {{ form_label(form.typeEnseignant, 'Type Enseignant', {'label_attr': {'class': 'form-label'}}) }}
    {{ form_widget(form.typeEnseignant, {'attr': {'class': 'form-control'}}) }}
</div>


{{ form_end(form) }}

{% endblock %}

templates/enseignant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de l'enseignant{% endblock %}

{% block body %}
    <h1>Détails de l'enseignant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom :</th>
                <td>{{ enseignant.utilisateur.lastName }}</td>
            </tr>
            <tr>
                <th>Prénom :</th>
                <td>{{ enseignant.utilisateur.firstName }}</td>
            </tr>
            <tr>
                <th>Type d'enseignant :</th>
                <td>{{ enseignant.typeEnseignant.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_enseignant_index') }}" class="btn btn-secondary">Retour à la liste</a>
    <a href="{{ path('app_enseignant_edit', {'id': enseignant.id}) }}" class="btn btn-primary">Modifier</a>
{% endblock %}